using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using dbll3.UC.rtfFormat;
namespace dbll3.UC
{
    public class TSQLKeyFromat: rtfFormat.ItemCollections
    {
        public TSQLKeyFromat()
        {
            base ._items.Add ("keywords",new Item(System.Drawing.Color.Blue,System.Drawing.Color.White ,"",
                new KeyType("add"),
                new KeyType("all"),
                new KeyType("alter"),
                new KeyType("and"),
                new KeyType("any"),
                new KeyType("as"),
                new KeyType("asc"),
                new KeyType("authorization"),
                new KeyType("backup"),
                new KeyType("begin"),
                new KeyType("between"),
                new KeyType("break"),
                new KeyType("browse"),
                new KeyType("bulk"),
                new KeyType("by"),
                new KeyType("cascade"),
                new KeyType("case"),
                new KeyType("check"),
                new KeyType("checkpoint"),
                new KeyType("close"),
                new KeyType("clustered"),
                new KeyType("coalesce"),
                new KeyType("collate"),
                new KeyType("column"),
                new KeyType("commit"),
                new KeyType("compute"),
                new KeyType("constraint"),
                new KeyType("contains"),
                new KeyType("containstable"),
                new KeyType("continue"),
                new KeyType("convert"),
                new KeyType("create"),
                new KeyType("cross"),
                new KeyType("current"),
                new KeyType("current_date"),
                new KeyType("current_time"),
                new KeyType("current_timestamp"),
                new KeyType("current_user"),
                new KeyType("cursor"),
                new KeyType("database"),
                new KeyType("dbcc"),
                new KeyType("deallocate"),
                new KeyType("declare"),
                new KeyType("default"),
                new KeyType("delete"),
                new KeyType("deny"),
                new KeyType("desc"),
                new KeyType("disk"),
                new KeyType("distinct"),
                new KeyType("distributed"),
                new KeyType("double"),
                new KeyType("drop"),
                new KeyType("dump"),
                new KeyType("else"),
                new KeyType("end"),
                new KeyType("errlvl"),
                new KeyType("escape"),
                new KeyType("except"),
                new KeyType("exec"),
                new KeyType("execute"),
                new KeyType("exists"),
                new KeyType("exit"),
                new KeyType("external"),
                new KeyType("fetch"),
                new KeyType("file"),
                new KeyType("fillfactor"),
                new KeyType("for"),
                new KeyType("foreign"),
                new KeyType("freetext"),
                new KeyType("freetexttable"),
                new KeyType("full"),
                new KeyType("function"),
                new KeyType("goto"),
                new KeyType("grant"),
                new KeyType("group"),
                new KeyType("having"),
                new KeyType("holdlock"),
                new KeyType("identity"),
                new KeyType("identity_insert"),
                new KeyType("identitycol"),
                new KeyType("if"),
                new KeyType("in"),
                new KeyType("index"),
                new KeyType("inner"),
                new KeyType("insert"),
                new KeyType("intersect"),
                new KeyType("into"),
                new KeyType("is"),
                new KeyType("join"),
                new KeyType("key"),
                new KeyType("kill"),
                new KeyType("left"),
                new KeyType("lineno"),
                new KeyType("load"),
                new KeyType("merge"),
                new KeyType("national"),
                new KeyType("nocheck"),
                new KeyType("nonclustered"),
                new KeyType("not"),
                new KeyType("null"),
                new KeyType("nullif"),
                new KeyType("of"),
                new KeyType("off"),
                new KeyType("offsets"),
                new KeyType("on"),
                new KeyType("open"),
                new KeyType("opendatasource"),
                new KeyType("openquery"),
                new KeyType("openrowset"),
                new KeyType("openxml"),
                new KeyType("option"),
                new KeyType("or"),
                new KeyType("order"),
                new KeyType("outer"),
                new KeyType("over"),
                new KeyType("percent"),
                new KeyType("pivot"),
                new KeyType("plan"),
                new KeyType("precision"),
                new KeyType("primary"),
                new KeyType("print"),
                new KeyType("proc"),
                new KeyType("procedure"),
                new KeyType("public"),
                new KeyType("raiserror"),
                new KeyType("read"),
                new KeyType("readtext"),
                new KeyType("reconfigure"),
                new KeyType("references"),
                new KeyType("replication"),
                new KeyType("restore"),
                new KeyType("restrict"),
                new KeyType("return"),
                new KeyType("revert"),
                new KeyType("revoke"),
                new KeyType("right"),
                new KeyType("rollback"),
                new KeyType("rowcount"),
                new KeyType("rowguidcol"),
                new KeyType("rule"),
                new KeyType("save"),
                new KeyType("schema"),
                new KeyType("securityaudit"),
                new KeyType("select"),
                new KeyType("semantickeyphrasetable"),
                new KeyType("semanticsimilaritydetailstable"),
                new KeyType("semanticsimilaritytable"),
                new KeyType("session_user"),
                new KeyType("set"),
                new KeyType("setuser"),
                new KeyType("shutdown"),
                new KeyType("some"),
                new KeyType("statistics"),
                new KeyType("system_user"),
                new KeyType("table"),
                new KeyType("tablesample"),
                new KeyType("textsize"),
                new KeyType("then"),
                new KeyType("top"),
                new KeyType("tran"),
                new KeyType("transaction"),
                new KeyType("trigger"),
                new KeyType("truncate"),
                new KeyType("try_convert"),
                new KeyType("tsequal"),
                new KeyType("union"),
                new KeyType("unique"),
                new KeyType("unpivot"),
                new KeyType("update"),
                new KeyType("updatetext"),
                new KeyType("use"),
                new KeyType("user"),
                new KeyType("values"),
                new KeyType("varying"),
                new KeyType("view"),
                new KeyType("waitfor"),
                new KeyType("when"),
                new KeyType("where"),
                new KeyType("while"),
                new KeyType("with"),
                new KeyType("withingroup"),
                new KeyType("writetext"),
                new KeyType("from")
                ));
            base._items.Add("breaket",
                new Item( System.Drawing.Color.Gray , System.Drawing.Color.White,"",
                    new KeyType("("),
                    new KeyType("{"),
                    new KeyType(")"),
                    new KeyType("}")));

            base._items.Add("operation",
                new Item(System.Drawing.Color.Gray , System.Drawing.Color.White,"",
                    new KeyType("like"),
                    new KeyType("+"),
                    new KeyType("-"),
                    new KeyType("*"),
                    new KeyType("/"),
                    new KeyType("^"),
                    new KeyType("%"),
                    new KeyType("and"),
                    new KeyType("or"),
                    new KeyType("xor")
                    ));
            base._items.Add("operation2",
                new Item(System.Drawing.Color.Red, System.Drawing.Color.White, "",
                    new KeyType("'")
                    ));
            base._items.Add("function",
                new Item(System.Drawing.Color.LawnGreen , System.Drawing.Color.White,"",
                    new KeyType("sin",true),
                    new KeyType("cos", true),
                    new KeyType("tan", true),
                    new KeyType("sinh", true),
                    new KeyType("cosh", true),
                    new KeyType("tanh", true),
                    new KeyType("asin", true),
                    new KeyType("acos", true),
                    new KeyType("atan", true),
                    new KeyType("log", true),
                    new KeyType("ln", true),
                    new KeyType("sqrt", true)));

            base._items.Add("REM", new Item(System.Drawing.Color.Green , System.Drawing.Color.White,"",
                    new KeyType("//",true,true ),
                    new KeyType("'", true, true)));

            //base._items.Add("customfunction", new Item(System.Drawing.Color.Tomato, System.Drawing.Color.White,""));

            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
            //base._items.Add("operation", new Item("", System.Drawing.Color.Blue, System.Drawing.Color.White));
        }
    }
}
